/**
 * The experience lifecycle: record, corroborate, promote, retire.
 *
 * Three archived failure modes shape this module.
 *
 * *Nothing was ever promoted.* Promotion required operator-registered hashes and
 * a 2–32 run replay, so after 139 cycles the store held zero confirmed facts.
 * Grading is now automatic ({@link gradeEvidence}) and promotion is a small
 * counter.
 *
 * *A single success became global policy.* The archived rules forbade it in
 * prose but had no mechanism. Here a lesson only leaves its workspace once
 * **two distinct workspaces** have independently reported it, which is counted,
 * not asserted.
 *
 * *Failures never demoted anything.* Consecutive failed outcomes now retire a
 * record immediately, and a never-reused low-importance record ages out.
 */
import { createHash, randomBytes } from 'node:crypto'
import { existsSync } from 'node:fs'
import { isAbsolute, join } from 'node:path'
                                               
import {
  corroborationCount, deleteRecord, findByFingerprint, getRecord, noteCorrection,
  noteCorroboration, noteUsage, readMeta, upsert, writeMeta, confirmedAfter,
  workspaceRecordsByFingerprint, candidateSiblings, pruneCorroboration, checkpointWal,
  candidateRecords, latestCorrection,
} from './db.js'
                                                    
import { gradeEvidence,                    } from './evidence.js'
import { joinTrigger } from './anchors.js'
import { importance, RESIDENT_EVIDENCE, RETIRE_FLOOR } from './rank.js'
                                                                                

const DAY = 86_400_000

/** Days after `review_after` before an unused record is retired. */
export const REVIEW_GRACE_DAYS = 30

/** Age at which a never-reused, low-importance record is retired. */
export const STALE_DAYS = 90

/** Where the maintenance scan resumes between passes. */
const CURSOR_KEY = 'maintenance_cursor'

/** Fold away differences that do not change what a record asserts. */
export function normalizeContent(text        )         {
  return text.normalize('NFKC').toLowerCase().replace(/\s+/g, ' ').trim()
}

/**
 * A comparison key for titles, with everything but letters and digits removed.
 *
 * Titles are labels, and the records show how loosely they are written: a live pair
 * carried one claim as `…重载「已加载 bundle」的模块` and `…重载已加载 bundle 的模块`,
 * differing only by the quotation marks around one word. Exact equality called those
 * two different claims, so the candidate they shared was never retired. Folding
 * punctuation and spacing is what lets the title serve as the claim-level handle at
 * all — it is a weaker key than the content fingerprint on purpose, and the action
 * taken on a match is reversible for the same reason.
 */
export function titleKey(title        )         {
  return title.toLowerCase().replace(/[^\p{L}\p{N}]+/gu, '')
}

/**
 * Content identity.
 *
 * Identity is the assertion and its kind, **not the title**. The title is a
 * label — often generated by summarising the body — so two workspaces that
 * independently learn the same lesson routinely label it differently
 * (`已核验静态：门禁风险` versus `门禁风险`). When the title was part of the
 * fingerprint those two produced different identities, which meant the
 * corroboration table never counted them and a lesson learned twice in two
 * projects could never be promoted to domain scope. The audit of the archived
 * tree found 28 such pairs: identical bodies, differing labels.
 *
 * Two records with genuinely different bodies still differ here, which is the
 * distinction that matters.
 */
export function fingerprint(kind      , body        )         {
  return createHash('sha256')
    .update([kind, normalizeContent(body)].join('\u0000'))
    .digest('hex')
    .slice(0, 32)
}

/** 20 hex characters. Random, and never used for ordering. */
export function newId()         {
  return randomBytes(10).toString('hex')
}

                                
                     
                                                                                
                
                                                                                         
               
            
               
              
                  
                      
                 
                    
     
                                                                                
    
                                                                                              
                                                                                         
                                                                                           
                                                                                            
     
                               
                                                                           
                
     
                                                            
    
                                                                                
                                                                                
                                                                               
                                             
     
                    
                                                                                     
                      
                   
             
 

                                                                                       

                                 
                          
                      
                 
                                                                                      
                      
                                                                   
                
                                                                     
                        
     
                                                                            
    
                                                                                           
                                                                                        
                                                                                          
     
                  
 

/**
 * Record one fact, experience or strategy.
 *
 * Idempotent by content: re-reporting the same claim corroborates the existing
 * record instead of duplicating it, and only a verified grade can lift a
 * candidate to confirmed.
 */
export function remember(db              , input               )                 {
  const title = input.title.trim()
  const body = input.body.trim()
  if (title === '' || body === '') {
    throw new TypeError('experience-memory: title and body are required')
  }
  const scope        = input.scope ?? 'workspace'
  const domain = input.domain.trim()
  if (scope === 'domain' && domain === '') {
    // The remedy goes in the message. This exact error was the tenth most frequent failure in
    // a seven-day audit (10 times, 3 sessions) and it says what is wrong without saying what
    // to do — which is how the same caller hits it twice in one session.
    throw new TypeError(
      'experience-memory: this workspace has no resolved domain, so a domain-scoped record '
      + 'cannot be filed. Use the default workspace scope, or give the workspace a domain '
      + 'first (package.json#name, .dsh/memory.yml, or the `defaultDomain` config).',
    )
  }

  const kind = input.kind
  const contentFingerprint = fingerprint(kind, body)

  // A window that has already closed, or one that is not a number, is a caller
  // mistake. Applying it would retire the record on the next pass, which looks
  // like the plugin losing data rather than the caller asking for the impossible.
  for (const [name, value] of [['expiresAt', input.expiresAt], ['reviewAfter', input.reviewAfter]]         ) {
    if (value === undefined) continue
    if (!Number.isFinite(value)) {
      throw new TypeError(`experience-memory: ${name} must be a finite timestamp, got ${String(value)}`)
    }
    if (value <= input.now) {
      throw new TypeError(`experience-memory: ${name} must be in the future, got ${new Date(value).toISOString()}`)
    }
  }

  noteCorroboration(db, contentFingerprint, input.workspaceId, input.now)
  const corroborations = corroborationCount(db, contentFingerprint)

  const verdict = gradeEvidence({
    quote: input.quote,
    sourceRef: input.sourceRef,
    workspaceRoot: input.agent?.session?.header?.cwd ?? process.cwd(),
    agent: input.agent,
  })
  const verified = RESIDENT_EVIDENCE.has(verdict.grade)
  const existing = findByFingerprint(db, contentFingerprint, scope, input.workspaceId, domain)

  if (existing !== undefined) {
    const promoted = existing.status === 'candidate' && verified
    // A retired record can come back, but only past two guards, because "retired" is
    // sometimes a decision rather than an accident. An explicit `memory_forget` is a
    // decision (`actor: 'agent'`), and a record a graded successor replaced stays replaced.
    // Everything else — maintenance ageing it out, a harvest sweep, a fail-streak demotion —
    // is mechanical, and a fresh *verified* passage outranks it.
    const retired = existing.status === 'retired'
    const superseded = existing.supersededBy !== null
    const vetoed = retired && !superseded && latestCorrection(db, existing.id)?.actor === 'agent'
    const revive = retired && !superseded && !vetoed && verified
    // Only a *fresh, checkable* passage brings a retired record back. The grade already
    // stored on the record is deliberately not enough: it says the claim was checkable once,
    // not that anything still is, and retirement is sometimes the store's only defence
    // against a record that kept misleading (two failed outcomes retire one).
    //
    // Saying only `corroborated` is what let a caller believe a retired record had been
    // recorded again: the word reads like success while the record stays invisible. Live
    // store, 2026-09-23 — a session re-reported a retired lesson, read `corroborated`, and
    // moved on. So a report that cannot revive says so, and the store is left untouched.
    if (retired && !revive) {
      return {
        outcome: 'still-retired',
        record: existing,
        grade: verdict.grade,
        route: verdict.route,
        corroborations,
        revived: false,
        reason: superseded
          ? `retired and replaced by ${String(existing.supersededBy)}; re-reporting does not undo that`
          : vetoed
            ? 'retired by an explicit memory_forget; re-reporting the same content does not revive it'
            : `retired; only a checkable passage (verified-file/user/tool) brings it back, and this report was ${verdict.grade}`,
      }
    }
    const record               = {
      ...existing,
      // A verified grade upgrades a weaker one; a weaker grade never downgrades.
      evidence: verified ? verdict.grade : existing.evidence,
      status: revive || promoted ? 'confirmed' : existing.status,
      needsReview: revive || promoted ? null : existing.needsReview,
      distinctWorkspaces: Math.max(existing.distinctWorkspaces, corroborations),
      // Re-reporting the same claim with a fresh passage is re-verification, so a
      // new window replaces the old one rather than being ignored.
      expiresAt: input.expiresAt ?? existing.expiresAt,
      reviewAfter: input.reviewAfter ?? existing.reviewAfter,
      updatedAt: input.now,
    }
    upsert(db, record)
    if (revive) {
      noteCorrection(db, record.id, 'experience-memory', 'revived by a fresh verified report', input.now)
    }
    return {
      outcome: 'corroborated', record, grade: verdict.grade, route: verdict.route,
      reason: verdict.reason, corroborations, revived: revive,
    }
  }

  const record               = {
    id: newId(),
    workspaceId: input.workspaceId,
    domain,
    scope,
    kind,
    status: verified ? 'confirmed' : 'candidate',
    evidence: verdict.grade,
    title,
    body,
    trigger: joinTrigger(input.trigger?.trim() ?? '', input.recallFor ?? []),
    failureMode: input.failureMode?.trim() ?? '',
    lesson: input.lesson?.trim() ?? '',
    sourceRef: input.sourceRef?.trim() ?? '',
    reuseCount: 0,
    successCount: 0,
    failureCount: 0,
    failStreak: 0,
    retrieveCount: 0,
    lastRetrievedAt: null,
    distinctWorkspaces: corroborations,
    createdAt: input.now,
    occurredAt: input.now,
    updatedAt: input.now,
    lastUsedAt: null,
    reviewAfter: input.reviewAfter ?? null,
    expiresAt: input.expiresAt ?? null,
    contentFingerprint,
    supersededBy: null,
    needsReview: verified ? null : 'awaiting a second observation or a verified passage',
  }
  upsert(db, record)

  // A candidate left by an earlier attempt at the same claim is not knowledge — it is
  // the same sentence twice, once weak. Live stores showed 3-4 such pairs, all formed
  // the same way: record without a passage, see it graded `inferred`, record it again.
  // Identity here is the assertion rather than the title, so a reworded body is a
  // *different* record and the earlier one stayed forever: invisible, un-injectable,
  // and swept by nothing. This runs for every write, not only a graded one: a caller
  // re-recording after a second failed attempt was leaving a pile of `inferred`
  // duplicates that nothing collected either.
  supersedeWeakerCandidates(db, record, input.now)

  // A lesson earned in one workspace stays there until a second, different
  // workspace reports the same content. That is the whole barrier between a
  // local quirk and a domain-wide rule.
  if (scope === 'workspace' && domain !== '' && corroborations >= 2) {
    const shared = promoteToDomain(db, record, domain, corroborations, input.now)
    return { outcome: 'promoted', record: shared, grade: verdict.grade, route: verdict.route, reason: verdict.reason, corroborations, revived: false }
  }

  return { outcome: 'created', record, grade: verdict.grade, route: verdict.route, reason: verdict.reason, corroborations, revived: false }
}

/**
 * Retire candidates this record has just replaced.
 *
 * The handle is the title, because that is the only thing two differently worded
 * versions of one claim still share. Matching on the body instead was the first idea
 * and it does not work: the real pairs were rewrites, so their token overlap sat far
 * below any near-duplicate threshold.
 *
 * Comparing titles exactly does not work either, and a live store proved it: one pair
 * differed only by the 「」 around a single word, so the candidate was left behind. The
 * comparison therefore folds punctuation and spacing — see {@link titleKey}.
 *
 * A shared title is still a weak signal, and it is treated as one: the loser is
 * *retired*, never deleted, with `supersededBy` pointing at the graded record and the
 * correction log recording why. Retirement is reversible, so a wrong call costs a
 * candidate that can be brought back, while the case this fixes costs an invisible
 * duplicate that nothing would ever remove.
 */
function supersedeWeakerCandidates(db              , record              , now        )       {
  const wanted = titleKey(record.title)
  if (wanted === '') return
  // The reason has to describe the replacement that actually happened. This sentence used
  // to be the literal "the same claim recorded with a verifiable passage" on every path,
  // and a caller caught it: two *failed* writes produced a retirement whose stated ground
  // was a passage neither record had. A reason that names a grade must read the grade.
  const graded = record.status === 'confirmed'
  const because = graded
    ? `the same claim recorded with a verifiable passage (${record.evidence})`
    : `the same claim recorded again later, with no verifiable passage either (${record.evidence}) `
      + '— one ungraded copy is kept rather than two'
  for (const sibling of candidateSiblings(db, record.workspaceId)) {
    if (sibling.id === record.id) continue
    if (titleKey(sibling.title) !== wanted) continue
    upsert(db, {
      ...sibling,
      status: 'retired',
      needsReview: null,
      supersededBy: record.id,
      updatedAt: now,
    })
    noteCorrection(
      db, sibling.id, 'experience-memory',
      `superseded by ${record.id}: ${because}`,
      now, record.id,
    )
  }
}

/**
 * Move a corroborated workspace record into its domain.
 *
 * Every other workspace copy of the same content is merged in and retired with
 * a supersession link, so the store never holds one lesson twice at two scopes.
 * Leaving the earlier copies behind would also mean the lesson kept being
 * injected from a workspace-local row that promotion was supposed to replace.
 */
function promoteToDomain(
  db              ,
  record              ,
  domain        ,
  corroborations        ,
  now        ,
)               {
  const existingTarget = findByFingerprint(db, record.contentFingerprint, 'domain', '', domain)

  let shared              
  if (existingTarget !== undefined) {
    shared = {
      ...existingTarget,
      evidence: RESIDENT_EVIDENCE.has(record.evidence) ? record.evidence : existingTarget.evidence,
      status: 'confirmed',
      reuseCount: existingTarget.reuseCount + record.reuseCount,
      successCount: existingTarget.successCount + record.successCount,
      failureCount: existingTarget.failureCount + record.failureCount,
      distinctWorkspaces: Math.max(existingTarget.distinctWorkspaces, corroborations),
      updatedAt: now,
    }
    upsert(db, shared)
  } else {
    // Corroboration is itself the evidence: two workspaces reached this claim
    // independently. Promoting the scope without promoting the status would
    // leave a domain record that is still a candidate, and candidates are never
    // injected — the promotion would be invisible to the model.
    shared = {
      ...record,
      scope: 'domain',
      domain,
      status: 'confirmed',
      needsReview: null,
      distinctWorkspaces: Math.max(record.distinctWorkspaces, corroborations),
      updatedAt: now,
    }
    upsert(db, shared)
  }

  // Absorb and retire every workspace copy that is not the domain record itself.
  for (const copy of workspaceRecordsByFingerprint(db, record.contentFingerprint)) {
    if (copy.id === shared.id) continue
    const absorbed               = {
      ...shared,
      reuseCount: shared.reuseCount + copy.reuseCount,
      successCount: shared.successCount + copy.successCount,
      failureCount: shared.failureCount + copy.failureCount,
      updatedAt: now,
    }
    upsert(db, absorbed)
    shared = absorbed
    upsert(db, { ...copy, status: 'retired', needsReview: null, supersededBy: shared.id, updatedAt: now })
    noteCorrection(db, copy.id, 'experience-memory', `merged into domain record ${shared.id}`, now, shared.id)
  }

  return shared
}

                             
                  
                                
                    
               
             
                                                                                  
                         
 

                              
                                             
                       
                     
 

/**
 * Link one real outcome to a record.
 *
 * A failure is the only signal that can demote a confirmed record without a
 * human, because a wrong memory that keeps being recalled is worse than a
 * missing one.
 */
export function recordUsage(db              , input            )              {
  const record = getRecord(db, input.recordId)
  if (record === undefined) return { outcome: 'missing' }
  noteUsage(db, record.id, input.outcome, input.now, input.sessionId, input.turn)

  const success = input.outcome === 'success'
  const failStreak = success ? 0 : record.failStreak + 1
  const retired = !success && failStreak >= input.failStreakLimit
  const updated               = {
    ...record,
    reuseCount: record.reuseCount + 1,
    successCount: record.successCount + (success ? 1 : 0),
    failureCount: record.failureCount + (success ? 0 : 1),
    failStreak,
    lastUsedAt: input.now,
    updatedAt: input.now,
    status: retired ? 'retired' : record.status,
    needsReview: retired ? `${failStreak} consecutive failed outcomes; demoted without assuming causality` : record.needsReview,
  }
  upsert(db, updated)
  if (retired) {
    noteCorrection(db, record.id, 'experience-memory', `${failStreak} consecutive failed outcomes`, input.now)
  }
  return { outcome: retired ? 'retired' : 'recorded', record: updated, failStreak }
}

                              
                  
                
                                                                             
               
                                                                       
                 
             
 

                                                            

/**
 * Retire a record, or delete it outright.
 *
 * Retirement is the default because it is reversible and because the audit
 * entry it writes — which names the id and the reason but never the content —
 * is the only thing that should survive a "forget this".
 */
export function forget(db              , input             )                {
  const record = getRecord(db, input.recordId)
  if (record === undefined) return 'missing'
  if (input.purge === true) {
    noteCorrection(db, record.id, input.actor, `purged: ${input.reason}`, input.now)
    deleteRecord(db, record.id)
    return 'purged'
  }
  upsert(db, { ...record, status: 'retired', needsReview: null, updatedAt: input.now })
  noteCorrection(db, record.id, input.actor, input.reason, input.now)
  return 'retired'
}

                               
                     
                                                                                      
                
                             
             
 

                                                    

/**
 * File one harvested sentence as a candidate.
 *
 * This deliberately does **not** go through {@link remember}. `remember` grades, and a
 * grade is a judgement about a claim — but the harvester does not have a claim, it has a
 * sentence it noticed. Writing straight to the store with `origin: 'harvest'` keeps that
 * distinction in the data instead of in a convention: a harvested row is a candidate by
 * construction, the always-on layer will not look at it, and the only route to becoming a
 * real record is the model saying the same thing again, at which point the ordinary
 * evidence gate decides on its merits.
 *
 * Identity is the content, as everywhere else, so a sentence harvested twice is one row.
 */
export function harvest(db              , input              )                 {
  const body = input.candidate.text.trim()
  if (body === '') return 'duplicate'
  const contentFingerprint = fingerprint('fact', body)
  if (findByFingerprint(db, contentFingerprint, 'workspace', input.workspaceId, input.domain) !== undefined) {
    return 'duplicate'
  }
  upsert(db, {
    id: newId(),
    workspaceId: input.workspaceId,
    domain: input.domain,
    scope: 'workspace',
    kind: 'fact',
    status: 'confirmed',
    title: input.candidate.title,
    body,
    trigger: '',
    failureMode: '',
    lesson: '',
    sourceRef: '',
    reuseCount: 0,
    successCount: 0,
    failureCount: 0,
    failStreak: 0,
    retrieveCount: 0,
    lastRetrievedAt: null,
    distinctWorkspaces: 1,
    createdAt: input.now,
    occurredAt: input.now,
    updatedAt: input.now,
    lastUsedAt: null,
    reviewAfter: null,
    expiresAt: null,
    contentFingerprint,
    supersededBy: null,
    // Saying what it is, where the model will read it: a harvested row is raw material
    // waiting for a judgement, and the review note is the only prompt it will ever get.
    needsReview: `采集自一轮会话（${input.candidate.signal}）——确认它成为经验，或丢弃`,
    status: 'candidate',
    evidence: 'inferred',
    origin: 'harvest',
    harvestSignal: input.candidate.signal,
  })
  return 'created'
}

/**
 * Retire harvested candidates that nothing ever did anything with, and any that overflow
 * the pool.
 *
 * The maintenance pass used to look only at confirmed records, so a candidate was
 * immortal: nothing aged it out, and only a graded record with the same title retired it.
 * That was tolerable while candidates were rare and is not tolerable once a harvester is
 * filling the pool, which is why both rules live here.
 *
 * A candidate that was *searched out* is kept regardless of age — someone reached for it,
 * which is the one piece of evidence a candidate can have while still unconfirmed.
 */
function sweepCandidates(
  db              ,
  now        ,
  ttlDays        ,
  poolLimit        ,
)                                    {
  const live = candidateRecords(db, poolLimit + CANDIDATE_SWEEP_LIMIT)
  const cutoff = now - ttlDays * DAY
  const retire = (record              , reason        )       => {
    upsert(db, { ...record, status: 'retired', needsReview: null, updatedAt: now })
    noteCorrection(db, record.id, 'experience-memory', reason, now)
  }

  let aged = 0
  const survivors                 = []
  for (const record of live) {
    if (record.createdAt < cutoff && record.retrieveCount === 0) {
      retire(record, `maintenance: 采集的候选 ${ttlDays} 天无人确认也无人查过`)
      aged += 1
      continue
    }
    survivors.push(record)
  }

  let evicted = 0
  const overflow = survivors.length - poolLimit
  if (overflow > 0) {
    for (const record of survivors.slice(0, overflow)) {
      retire(record, `maintenance: 候选池超过 ${poolLimit} 条，退役最旧的一条`)
      evicted += 1
    }
  }
  return { aged, evicted }
}

                                
             
                   
                                                                  
                           
                                                                     
                             
     
                                                                                             
    
                                                                                                 
                                                                                                
                          
     
                        
 

/** How far past the pool ceiling the candidate sweep is allowed to look. */
const CANDIDATE_SWEEP_LIMIT = 64

/**
 * Fallbacks for the candidate sweep when a caller passes none.
 *
 * They mirror the config defaults rather than importing them, because `config.ts` imports
 * nothing from here and a cycle would be a worse price than repeating two numbers that the
 * suite already checks agree.
 */
const CANDIDATE_TTL_DAYS_DEFAULT = 14
const CANDIDATE_POOL_DEFAULT = 200

                                 
                 
                 
                                           
                                 
                                                                              
                              
                                                                              
                        
                                                                            
                           
                                                                                      
                         
 

/** Why one record should leave the resident pool, or `undefined` to keep it. */
export function retirementReason(record              , now        )                     {
  if (record.expiresAt !== null && record.expiresAt <= now) return 'expired'
  if (record.reviewAfter !== null
    && now - record.reviewAfter > REVIEW_GRACE_DAYS * DAY
    && record.reuseCount === 0
    && record.successCount === 0) {
    return 'review overdue and never reused'
  }
  const anchor = record.lastUsedAt ?? record.createdAt
  const aged = now - anchor > STALE_DAYS * DAY
  if (aged && record.reuseCount === 0) {
    const score = importance({
      evidence: record.evidence,
      successCount: record.successCount,
      reuseCount: record.reuseCount,
      failStreak: record.failStreak,
      distinctWorkspaces: record.distinctWorkspaces,
      createdAt: record.createdAt,
      lastUsedAt: record.lastUsedAt,
      reviewAfter: record.reviewAfter,
      now,
    })
    if (score < RETIRE_FLOOR) return 'never reused and below the retire floor'
  }
  return undefined
}

/**
 * Marker written into `needsReview` when a record's cited file is no longer on disk.
 *
 * Prefixed so the symmetric case can clear exactly this flag and not a human's note.
 */
export const SOURCE_GONE = '出处文件已不存在：'

/**
 * Flag `verified-file` records whose cited file is no longer there.
 *
 * The evidence grade proves the quoted passage is *in* a file at the moment the record is
 * written. It does not promise the file will still exist in a week — files get renamed, moved,
 * cleaned up. And when it is gone the record becomes actively harmful: a real model reading it
 * back asks where the cited file is, fails to find it, and throws the whole record away rather
 * than trust a citation it cannot follow (measured; see `docs/DELIVERY-GAPS.md` §17).
 *
 * So maintenance checks the file, and flags rather than blocks: a cited file may legitimately
 * not exist *yet* (a record about something the lesson precedes) or may come back from a
 * restore. The flag is a note to a reader, not a downgrade — the record stays confirmed and
 * deliverable until someone looks at it.
 *
 * Runs over the same bounded, cursor-resumed batch the rest of maintenance scans, so a large
 * store never pays a full table walk. `workspaceRoot` is required to resolve the record's
 * workspace-relative path; without it nothing is checked, because guessing a root would flag
 * every record or none.
 */
export function checkProvenance(
  db              ,
  records                         ,
  workspaceRoot        ,
)         {
  if (workspaceRoot.trim() === '') return 0
  let flagged = 0
  for (const record of records) {
    if (record.evidence !== 'verified-file') continue
    const ref = String(record.sourceRef ?? '').trim()
    if (ref === '' || /^call_/i.test(ref)) continue
    // An absolute path cannot be resolved against the workspace and cannot be checked here;
    // it was not verifiable when the record was written either.
    if (isAbsolute(ref)) continue
    // Strip a trailing `:line` / `:line:col`, keeping any Windows drive colon out of the way
    // (a relative path has none).
    const path = ref.replace(/:\d+(?::\d+)?$/, '')
    if (path === '') continue
    const already = record.needsReview !== null && String(record.needsReview).startsWith(SOURCE_GONE)
    const exists = existsSync(join(workspaceRoot, path))
    if (!exists && !already) {
      upsert(db, { ...record, needsReview: `${SOURCE_GONE}${path}` })
      flagged += 1
    } else if (exists && already) {
      // The file came back (a restore, an un-delete). Clear the note rather than let a stale
      // warning outlive its own cause.
      upsert(db, { ...record, needsReview: null })
    }
  }
  return flagged
}

/**
 * One bounded maintenance pass: age out what nothing is using.
 *
 * Runs at turn end and never on the retrieval path, so a large store cannot
 * slow a search down. The scan resumes from a cursor and wraps, so repeated
 * passes cover everything without walking the whole table at once.
 */
export function maintain(db              , input               )                 {
  const batchSize = Math.max(1, Math.trunc(input.batchSize))
  const cursor = readMeta(db, CURSOR_KEY)
  let batch = confirmedAfter(db, cursor, batchSize)
  let wrapped = false
  if (batch.length === 0 && cursor !== '') {
    batch = confirmedAfter(db, '', batchSize)
    wrapped = true
  }

  // Provenance first: it does not retire anything, and a record that is about to be aged out
  // for never being used should still have its flag say why a reader distrusted it.
  const provenanceFlags = input.workspaceRoot === undefined
    ? 0
    : checkProvenance(db, batch, input.workspaceRoot)

  const reasons                         = {}
  let retired = 0
  for (const record of batch) {
    const reason = retirementReason(record, input.now)
    if (reason === undefined) continue
    forget(db, { recordId: record.id, reason: `maintenance: ${reason}`, actor: 'experience-memory', now: input.now })
    reasons[reason] = (reasons[reason] ?? 0) + 1
    retired += 1
  }

  const last = batch[batch.length - 1]
  if (last !== undefined) writeMeta(db, CURSOR_KEY, last.id)
  else writeMeta(db, CURSOR_KEY, '')

  // Stores written before `deleteRecord` learned to clean up after a purge still carry
  // the rows that would mis-count a future corroboration, so the sweep runs here too and
  // repairs them rather than waiting for the next purge of the same content.
  const orphanCorroborations = pruneCorroboration(db)

  // Candidates are swept here because nothing else sweeps them: the scan above only
  // reaches confirmed records, so without this a candidate is immortal.
  const candidates = sweepCandidates(
    db,
    input.now,
    input.candidateTtlDays ?? CANDIDATE_TTL_DAYS_DEFAULT,
    input.candidatePoolLimit ?? CANDIDATE_POOL_DEFAULT,
  )

  // Last, and best effort: fold the log back into the main file so the store is not one
  // file that is current plus one that carries everything recent.
  checkpointWal(db)

  return {
    scanned: batch.length,
    retired,
    reasons,
    orphanCorroborations,
    candidatesAged: candidates.aged,
    candidatesEvicted: candidates.evicted,
    provenanceFlags,
  }
}
