/**
 * The experience lifecycle: record, corroborate, promote, retire.
 *
 * Three archived failure modes shape this module.
 *
 * *Nothing was ever promoted.* Promotion required operator-registered hashes and
 * a 2–32 run replay, so after 139 cycles the store held zero confirmed facts.
 * Grading is now automatic ({@link gradeEvidence}) and promotion is a small
 * counter.
 *
 * *A single success became global policy.* The archived rules forbade it in
 * prose but had no mechanism. Here a lesson only leaves its workspace once
 * **two distinct workspaces** have independently reported it, which is counted,
 * not asserted.
 *
 * *Failures never demoted anything.* Consecutive failed outcomes now retire a
 * record immediately, and a never-reused low-importance record ages out.
 */
import { createHash, randomBytes } from 'node:crypto'
import type { DatabaseSync } from 'node:sqlite'
import {
  corroborationCount, deleteRecord, findByFingerprint, getRecord, noteCorrection,
  noteCorroboration, noteUsage, readMeta, upsert, writeMeta, confirmedAfter,
  workspaceRecordsByFingerprint,
} from './db.ts'
import { gradeEvidence, type SessionLike } from './evidence.ts'
import { importance, RESIDENT_EVIDENCE, RETIRE_FLOOR } from './rank.ts'
import type { Evidence, Kind, MemoryRecord, Scope } from './types.ts'

const DAY = 86_400_000

/** Days after `review_after` before an unused record is retired. */
export const REVIEW_GRACE_DAYS = 30

/** Age at which a never-reused, low-importance record is retired. */
export const STALE_DAYS = 90

/** Where the maintenance scan resumes between passes. */
const CURSOR_KEY = 'maintenance_cursor'

/** Fold away differences that do not change what a record asserts. */
export function normalizeContent(text: string): string {
  return text.normalize('NFKC').toLowerCase().replace(/\s+/g, ' ').trim()
}

/**
 * Content identity.
 *
 * Identity is the assertion and its kind, **not the title**. The title is a
 * label — often generated by summarising the body — so two workspaces that
 * independently learn the same lesson routinely label it differently
 * (`已核验静态：门禁风险` versus `门禁风险`). When the title was part of the
 * fingerprint those two produced different identities, which meant the
 * corroboration table never counted them and a lesson learned twice in two
 * projects could never be promoted to domain scope. The audit of the archived
 * tree found 28 such pairs: identical bodies, differing labels.
 *
 * Two records with genuinely different bodies still differ here, which is the
 * distinction that matters.
 */
export function fingerprint(kind: Kind, body: string): string {
  return createHash('sha256')
    .update([kind, normalizeContent(body)].join('\u0000'))
    .digest('hex')
    .slice(0, 32)
}

/** 20 hex characters. Random, and never used for ordering. */
export function newId(): string {
  return randomBytes(10).toString('hex')
}

export interface RememberInput {
  workspaceId: string
  /** The workspace's resolved domain, recorded even for a local-only lesson. */
  domain: string
  /** Defaults to `workspace`: a lesson stays where it was learned until corroborated. */
  scope?: Scope
  kind: Kind
  title: string
  body: string
  trigger?: string
  failureMode?: string
  lesson?: string
  sourceRef?: string
  /** The verbatim passage the claim rests on; enables a verified grade. */
  quote?: string
  agent?: SessionLike
  now: number
}

export type RememberOutcome = 'created' | 'corroborated' | 'promoted'

export interface RememberResult {
  outcome: RememberOutcome
  record: MemoryRecord
  grade: Evidence
  /** Why that grade, so the model can improve its next attempt. */
  reason: string
  /** How many distinct workspaces have now reported this content. */
  corroborations: number
}

/**
 * Record one fact, experience or strategy.
 *
 * Idempotent by content: re-reporting the same claim corroborates the existing
 * record instead of duplicating it, and only a verified grade can lift a
 * candidate to confirmed.
 */
export function remember(db: DatabaseSync, input: RememberInput): RememberResult {
  const title = input.title.trim()
  const body = input.body.trim()
  if (title === '' || body === '') {
    throw new TypeError('experience-memory: title and body are required')
  }
  const scope: Scope = input.scope ?? 'workspace'
  const domain = input.domain.trim()
  if (scope === 'domain' && domain === '') {
    throw new TypeError('experience-memory: a domain-scoped record needs a resolved domain')
  }

  const kind = input.kind
  const contentFingerprint = fingerprint(kind, body)
  noteCorroboration(db, contentFingerprint, input.workspaceId, input.now)
  const corroborations = corroborationCount(db, contentFingerprint)

  const verdict = gradeEvidence({
    quote: input.quote,
    sourceRef: input.sourceRef,
    workspaceRoot: input.agent?.session?.header?.cwd ?? process.cwd(),
    agent: input.agent,
  })
  const verified = RESIDENT_EVIDENCE.has(verdict.grade)
  const existing = findByFingerprint(db, contentFingerprint, scope, input.workspaceId, domain)

  if (existing !== undefined) {
    const promoted = existing.status === 'candidate' && verified
    const record: MemoryRecord = {
      ...existing,
      // A verified grade upgrades a weaker one; a weaker grade never downgrades.
      evidence: verified ? verdict.grade : existing.evidence,
      status: promoted ? 'confirmed' : existing.status,
      needsReview: promoted ? null : existing.needsReview,
      distinctWorkspaces: Math.max(existing.distinctWorkspaces, corroborations),
      updatedAt: input.now,
    }
    upsert(db, record)
    return { outcome: 'corroborated', record, grade: verdict.grade, reason: verdict.reason, corroborations }
  }

  const record: MemoryRecord = {
    id: newId(),
    workspaceId: input.workspaceId,
    domain,
    scope,
    kind,
    status: verified ? 'confirmed' : 'candidate',
    evidence: verdict.grade,
    title,
    body,
    trigger: input.trigger?.trim() ?? '',
    failureMode: input.failureMode?.trim() ?? '',
    lesson: input.lesson?.trim() ?? '',
    sourceRef: input.sourceRef?.trim() ?? '',
    reuseCount: 0,
    successCount: 0,
    failureCount: 0,
    failStreak: 0,
    distinctWorkspaces: corroborations,
    createdAt: input.now,
    occurredAt: input.now,
    updatedAt: input.now,
    lastUsedAt: null,
    reviewAfter: null,
    expiresAt: null,
    contentFingerprint,
    supersededBy: null,
    needsReview: verified ? null : 'awaiting a second observation or a verified passage',
  }
  upsert(db, record)

  // A lesson earned in one workspace stays there until a second, different
  // workspace reports the same content. That is the whole barrier between a
  // local quirk and a domain-wide rule.
  if (scope === 'workspace' && domain !== '' && corroborations >= 2) {
    const shared = promoteToDomain(db, record, domain, corroborations, input.now)
    return { outcome: 'promoted', record: shared, grade: verdict.grade, reason: verdict.reason, corroborations }
  }

  return { outcome: 'created', record, grade: verdict.grade, reason: verdict.reason, corroborations }
}

/**
 * Move a corroborated workspace record into its domain.
 *
 * Every other workspace copy of the same content is merged in and retired with
 * a supersession link, so the store never holds one lesson twice at two scopes.
 * Leaving the earlier copies behind would also mean the lesson kept being
 * injected from a workspace-local row that promotion was supposed to replace.
 */
function promoteToDomain(
  db: DatabaseSync,
  record: MemoryRecord,
  domain: string,
  corroborations: number,
  now: number,
): MemoryRecord {
  const existingTarget = findByFingerprint(db, record.contentFingerprint, 'domain', '', domain)

  let shared: MemoryRecord
  if (existingTarget !== undefined) {
    shared = {
      ...existingTarget,
      evidence: RESIDENT_EVIDENCE.has(record.evidence) ? record.evidence : existingTarget.evidence,
      status: 'confirmed',
      reuseCount: existingTarget.reuseCount + record.reuseCount,
      successCount: existingTarget.successCount + record.successCount,
      failureCount: existingTarget.failureCount + record.failureCount,
      distinctWorkspaces: Math.max(existingTarget.distinctWorkspaces, corroborations),
      updatedAt: now,
    }
    upsert(db, shared)
  } else {
    // Corroboration is itself the evidence: two workspaces reached this claim
    // independently. Promoting the scope without promoting the status would
    // leave a domain record that is still a candidate, and candidates are never
    // injected — the promotion would be invisible to the model.
    shared = {
      ...record,
      scope: 'domain',
      domain,
      status: 'confirmed',
      needsReview: null,
      distinctWorkspaces: Math.max(record.distinctWorkspaces, corroborations),
      updatedAt: now,
    }
    upsert(db, shared)
  }

  // Absorb and retire every workspace copy that is not the domain record itself.
  for (const copy of workspaceRecordsByFingerprint(db, record.contentFingerprint)) {
    if (copy.id === shared.id) continue
    const absorbed: MemoryRecord = {
      ...shared,
      reuseCount: shared.reuseCount + copy.reuseCount,
      successCount: shared.successCount + copy.successCount,
      failureCount: shared.failureCount + copy.failureCount,
      updatedAt: now,
    }
    upsert(db, absorbed)
    shared = absorbed
    upsert(db, { ...copy, status: 'retired', needsReview: null, supersededBy: shared.id, updatedAt: now })
    noteCorrection(db, copy.id, 'experience-memory', `merged into domain record ${shared.id}`, now, shared.id)
  }

  return shared
}

export interface UsageInput {
  recordId: string
  outcome: 'success' | 'failure'
  sessionId?: string
  turn?: number
  now: number
  /** Consecutive failures that retire the record. Configurable, defaults to 2. */
  failStreakLimit: number
}

export interface UsageResult {
  outcome: 'recorded' | 'retired' | 'missing'
  record?: MemoryRecord
  failStreak?: number
}

/**
 * Link one real outcome to a record.
 *
 * A failure is the only signal that can demote a confirmed record without a
 * human, because a wrong memory that keeps being recalled is worse than a
 * missing one.
 */
export function recordUsage(db: DatabaseSync, input: UsageInput): UsageResult {
  const record = getRecord(db, input.recordId)
  if (record === undefined) return { outcome: 'missing' }
  noteUsage(db, record.id, input.outcome, input.now, input.sessionId, input.turn)

  const success = input.outcome === 'success'
  const failStreak = success ? 0 : record.failStreak + 1
  const retired = !success && failStreak >= input.failStreakLimit
  const updated: MemoryRecord = {
    ...record,
    reuseCount: record.reuseCount + 1,
    successCount: record.successCount + (success ? 1 : 0),
    failureCount: record.failureCount + (success ? 0 : 1),
    failStreak,
    lastUsedAt: input.now,
    updatedAt: input.now,
    status: retired ? 'retired' : record.status,
    needsReview: retired ? `${failStreak} consecutive failed outcomes; demoted without assuming causality` : record.needsReview,
  }
  upsert(db, updated)
  if (retired) {
    noteCorrection(db, record.id, 'experience-memory', `${failStreak} consecutive failed outcomes`, input.now)
  }
  return { outcome: retired ? 'retired' : 'recorded', record: updated, failStreak }
}

export interface ForgetInput {
  recordId: string
  reason: string
  /** Who asked. Tool calls pass `agent`; maintenance passes its own name. */
  actor: string
  /** `true` deletes the bytes. Defaults to a reversible retirement. */
  purge?: boolean
  now: number
}

export type ForgetOutcome = 'retired' | 'purged' | 'missing'

/**
 * Retire a record, or delete it outright.
 *
 * Retirement is the default because it is reversible and because the audit
 * entry it writes — which names the id and the reason but never the content —
 * is the only thing that should survive a "forget this".
 */
export function forget(db: DatabaseSync, input: ForgetInput): ForgetOutcome {
  const record = getRecord(db, input.recordId)
  if (record === undefined) return 'missing'
  if (input.purge === true) {
    noteCorrection(db, record.id, input.actor, `purged: ${input.reason}`, input.now)
    deleteRecord(db, record.id)
    return 'purged'
  }
  upsert(db, { ...record, status: 'retired', needsReview: null, updatedAt: input.now })
  noteCorrection(db, record.id, input.actor, input.reason, input.now)
  return 'retired'
}

export interface MaintainInput {
  now: number
  batchSize: number
}

export interface MaintainResult {
  scanned: number
  retired: number
  /** Why records were retired, counted. */
  reasons: Record<string, number>
}

/** Why one record should leave the resident pool, or `undefined` to keep it. */
export function retirementReason(record: MemoryRecord, now: number): string | undefined {
  if (record.expiresAt !== null && record.expiresAt <= now) return 'expired'
  if (record.reviewAfter !== null
    && now - record.reviewAfter > REVIEW_GRACE_DAYS * DAY
    && record.reuseCount === 0
    && record.successCount === 0) {
    return 'review overdue and never reused'
  }
  const anchor = record.lastUsedAt ?? record.createdAt
  const aged = now - anchor > STALE_DAYS * DAY
  if (aged && record.reuseCount === 0) {
    const score = importance({
      evidence: record.evidence,
      successCount: record.successCount,
      reuseCount: record.reuseCount,
      failStreak: record.failStreak,
      distinctWorkspaces: record.distinctWorkspaces,
      createdAt: record.createdAt,
      lastUsedAt: record.lastUsedAt,
      reviewAfter: record.reviewAfter,
      now,
    })
    if (score < RETIRE_FLOOR) return 'never reused and below the retire floor'
  }
  return undefined
}

/**
 * One bounded maintenance pass: age out what nothing is using.
 *
 * Runs at turn end and never on the retrieval path, so a large store cannot
 * slow a search down. The scan resumes from a cursor and wraps, so repeated
 * passes cover everything without walking the whole table at once.
 */
export function maintain(db: DatabaseSync, input: MaintainInput): MaintainResult {
  const batchSize = Math.max(1, Math.trunc(input.batchSize))
  const cursor = readMeta(db, CURSOR_KEY)
  let batch = confirmedAfter(db, cursor, batchSize)
  let wrapped = false
  if (batch.length === 0 && cursor !== '') {
    batch = confirmedAfter(db, '', batchSize)
    wrapped = true
  }

  const reasons: Record<string, number> = {}
  let retired = 0
  for (const record of batch) {
    const reason = retirementReason(record, input.now)
    if (reason === undefined) continue
    forget(db, { recordId: record.id, reason: `maintenance: ${reason}`, actor: 'experience-memory', now: input.now })
    reasons[reason] = (reasons[reason] ?? 0) + 1
    retired += 1
  }

  const last = batch[batch.length - 1]
  if (last !== undefined) writeMeta(db, CURSOR_KEY, last.id)
  else writeMeta(db, CURSOR_KEY, '')

  return { scanned: batch.length, retired, reasons }
}
